---
title: "Bonepile Data Summary"
author: "Annie Kellner"
date: "2/9/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, include=FALSE, message=FALSE}

rm(list = ls())

library(sf)
library(tidyverse)
library(amt)
library(tmap)
library(tmaptools)
library(adehabitatLT)
library(adehabitatHR)
library(data.table)
library(here)
library(conflicted)

conflicts_prefer(
  dplyr::filter()
)

```

```{r load-and-prep-data, message=FALSE, warning=FALSE, echo=FALSE}

# Bears

b <- readRDS(here("Data", "Derived-data", "DFs", "OG", "OG.Rds"))

# Bonepile points 

u <- b %>% filter(at_bonepile == 1)  # load all bonepile points
usf <- st_as_sf(u, coords = c("Xaa", "Yaa"), crs = 3338) %>% distinct() # seeing whether this eliminates duplicates. Appears to. 

# Alaska

#us <- st_read('./Data/Spatial/State_Shapefile/States_NAD83_Albers.shp') # From NPS state shapefile

#bb <- st_read('C:/Users/akell/OneDrive - Colostate/PhD/Polar_Bears_GIS/Rectangle/Rectangle.shp')

#bb <- st_transform(bb, 3338)

#ak <- us %>%
  #filter(STATE_ABBR == "AK") %>%
  #st_transform(3338) 

#ak <- st_crop(ak, bb)

```

```{r plot-all-points}

tmap_mode('view')

tm_shape(usf) + 
  tm_symbols(size = 0.2, col = "id", legend.col.show = FALSE)  
  #tm_shape(bone) + 
  #tm_symbols(size = 0.8, shape = 4, col = "black") +
  #m_legend(show = FALSE)

```

Number of locations per bear

```{r days-tracked}

# Create track in adehabitatLT

ltraj <- as.ltraj(xy=u[,c("Xaa","Yaa")], date=u$datetime, id=as.character(u$id))

summary <- summary(ltraj)

summary$DaysTrack <-round(difftime(summary$date.end, summary$date.begin, units="days"),digits=1)
summary <- dplyr::select(summary, id, date.begin, date.end, DaysTrack)
summary

summary$DaysTrack <- as.numeric(summary$DaysTrack)

summary(summary)

sd(summary$DaysTrack)
```
Data Years

# MCP's

```{r mcp}

used <- dplyr::select(used, id,geometry)
used.sp <- as_Spatial(used)

mcp95 <- mcp(used.sp, percent = 99)

tm_shape(ak) + 
  tm_polygons(col = "#ABF37E") + 
  tm_shape(mcp95) +
  tm_polygons(col = "id", alpha = 0.4, legend.show = FALSE)

```



# Plot used v. available points

```{r create-used-avail-pts, echo=FALSE}
# Make track with package amt

track <- make_track(used.df, X, Y, crs = sp::CRS("+init=epsg:3338"), id = id) # makes one big track with all animals
trk <- track %>% nest(data = -"id") # creates dataframes for each individual

# Create random points using 99 MCP for each individual

rsf <- data.frame(case_ = logical(), x_ = double(), y_ = double(), id = character())
ids <- unique(used.df$id)

for(i in 1:length(ids)){
  bear_trk = trk$data[[i]]
  hr = hr_mcp(bear_trk, levels = 0.99)
  rsf_pts = random_points(hr, n = 20*nrow(bear_trk), presence = bear_trk)
  rsf_pts$id = ids[i]
  rsf = rbind(rsf, rsf_pts)
}

```


```{r plot random v used}

# Plot random v matched points
ggplot(rsf, aes(x_, y_, color=case_))+
  geom_point()+
  facet_wrap(~id, scales="free")
```
 Used and available points for bonepile bears
 
 The 'blue' ("TRUE") points are more obvious here than in the step-selection. That makes sense because these points could be anywhere in the MCP whereas the step-selection available points are more limited?
