---
title: "Summary_non_bonepile"
author: "Annie Kellner"
date: "1/27/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r libraries, include = FALSE, message=FALSE}

rm(list = ls())

library(dplyr)
library(lubridate)
library(ggplot2)
library(amt)
library(sf)
library(tmap)
library(tmaptools)
library(adehabitatLT)
```

# Summary for all non-bonepile points

```{r load-data, include=FALSE, message=FALSE}

# Bears

used <- readRDS('./Data/all_non_bonepile_pts.Rds') # load all non-bonepile points

#used.sf <- st_as_sf(used, coords = c('X',"Y"), crs = 3338) # sf object for plotting all points

# Alaska

us <- st_read('./Data/Spatial/State_Shapefile/States_NAD83_Albers.shp') # From NPS state shapefile

bb <- st_read('C:/Users/akell/OneDrive - Colostate/PhD/Polar_Bears_GIS/Rectangle/Rectangle.shp')

bb <- st_transform(bb, 3338)

ak <- us %>%
  filter(STATE_ABBR == "AK") %>%
  st_transform(3338) 

ak <- st_crop(ak, bb)

# Bonepiles

bone <- st_read('./Data/Spatial/Bonepiles/bonepiles.shp')

```

```{r plot-all-points}

tmap_mode('view')

tm_shape(ak) + 
  tm_polygons(col = "#ABF37E") + 
  tm_shape(used.sf) + 
  tm_symbols(size = 0.2, col = "id") + 
  tm_shape(bone) + 
  tm_symbols(size = 0.8, shape = 4, col = "black") +
  tm_legend(show = FALSE)
  

```


```{r prep-data}

source('./Code/MyFunctions.R')

# Convert sf object to dataframe
used <- cbind(used, st_coordinates(used)) # separate coords from geometry columns into X and Y columns

used <- used %>%
  st_drop_geometry() %>%
  as.data.frame()

# Make track

track <- make_track(used, X, Y, datetime, id = id, crs = sp::CRS("+init=epsg:3338"))
tr <- track %>% nest(data = -"id") 

tr2 <- tr %>% # downsample to 2-hr fix rate
  mutate(steps = map(data, function(x)
    x %>% track_resample(rate = hours(2), tolerance = minutes(20)) %>% steps_by_burst()))

# Dataframe

df <- tr2 %>% select(id, steps) %>% unnest(cols = steps) 

```

# Summary stats for non-bonepile points

```{r number-of-points}

table(df$id)

```
Table showing number of locations per bear  

```{r days-tracked}

# Need to use adehabitatLT to get DaysTracked, so need to remove extra points (from 1-hr bears) from used df

t <- df %>%
  dplyr::select(id, t1_) %>%
  rename(datetime = t1_)

used2 <- used %>%
  semi_join(t)

# Create track in adehabitatLT

ltraj <- as.ltraj(xy=used2[,c("X","Y")], date=used2$datetime, id=as.character(used2$id))
summary <- summary(ltraj)

summary$DaysTrack <-round(difftime(summary$date.end, summary$date.begin, units="days"),digits=1)
summary

```
Should I remove bears with 4-5 days of coverage?

```{r}

first <- used2 %>%
  group_by(id) %>%
  slice_head() %>%
  mutate(yr = year(datetime))

ggplot(data = first, aes(x = yr)) + 
  geom_bar() + 
  scale_x_continuous("Year", 
                   breaks = c(2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015),
                   labels = c("2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015"))
```
Histogram showing years represented (count = number of bears)  


```{r steps-histogram}

steps <- tr2 %>% dplyr::select(id, steps) %>% unnest(cols = steps) 

ggplot(data = steps, aes(sl_)) + 
  geom_histogram()+ 
  facet_wrap(~id) + 
  xlab("step length (m)") + 
  ylab("Number of steps")
```

```{r turning-angle}

ggplot(data = steps, aes(ta_, fill = factor(id))) + 
  geom_density(alpha = 0.4)

```

# Used and Available Points

```{r}

ua <- steps %>% group_by(id) %>% random_steps(n_control = 20) # add random steps

# Plot random v matched points
ggplot(ua, aes(x2_, y2_, color=case_))+
  geom_point()+
  facet_wrap(~id, scales="free")

saveRDS(ua, './non_bp_pts_used_avail.Rds')
```

