---
title: "Methods_Data_Collection"
author: "Annie Kellner"
date: "2023-08-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r load libraries}

library(tidyverse)
library(here)
library(sf)
library(adehabitatLT)
library(tmap)
library(tmaptools)
library(knitr)
library(conflicted)

conflicts_prefer(
  dplyr::filter(),
  dplyr::select()
)
```
## Data Collection

```{r load-data}

# Bears

b <- readRDS(here("Data", "Derived-data", "DFs", "OG", "OG_090323.Rds"))

# GPS Data

fix <- readRDS(here("Data", "Derived-data", "DFs", "OG", "Fix_Rates.Rds"))

```

*For Data Collection paragraph:* 

# Bear IDs and Years

```{r ids-and-years}

table(b$animal, b$year)
length(unique(b$id)) # bear-summers
length(unique(b$animal))

```

* 25 bear years
* 23 individuals
* 2 bears with two years of data

# Tracking data

```{r adehabitatLT}

b <- as.data.frame(b)

ltraj <- as.ltraj(b[,c("Xaa","Yaa")], date=b$datetime, id=b$id, typeII = TRUE)

summary <- summary(ltraj)

summary$DaysTrack <-round(difftime(summary$date.end, summary$date.begin, units="days"),digits=1)

summary <- summary %>%
  select(id, date.begin, date.end, DaysTrack) %>%
  mutate(year = year(date.begin)) %>%
  mutate(DaysTrack = as.numeric(DaysTrack)) %>%
  arrange(year) 

summary(summary)

sd(summary$DaysTrack)
```

LATER: Can check whether missed fixes appear to be related to habitat variables. For now, say they aren't

```{r study-window}

start <- b %>%
  group_by(id) %>%
  slice_head()

summary(start)
sd(start$ordinal_date)

end <- b %>%
  group_by(id) %>%
  slice_tail()

summary(end)
sd(end$ordinal_date)
```

```{r bear-categories}

lf <- b %>%
  filter(landfall == 1)

l <- b %>%
  group_by(id) %>%
  slice_head() %>%
  filter(landfall == 0)

filter(b, departure_to_ice == 1)
filter(b, enter_den == 1)

```

# GPS Fix Rate Data

```{r}

fix$median <- round(fix$median, digits = 0)

table(fix$median)

```
## Corridor Tracking Data

```{r corridor-summary-stats}

u <- b %>% filter(at_bonepile == 0)  # load all bonepile points
u <- u %>%
  filter(!(id == "pb_32608.2008")) # AT SOME POINT, ADJUST BONEPILE DATES TO REFLECT BONEPILE-ONLY BEAR

# Create track in adehabitatLT

ltraj <- as.ltraj(xy=u[,c("Xaa","Yaa")], date=u$datetime, id=as.character(u$id))

summary <- summary(ltraj)

summary$DaysTrack <-round(difftime(summary$date.end, summary$date.begin, units="days"),digits=1)
summary <- dplyr::select(summary, id, date.begin, date.end, DaysTrack)
summary

summary$DaysTrack <- as.numeric(summary$DaysTrack)

summary(summary)

sd(summary$DaysTrack)

```

```{r step-length-plot}

# Make track (amt package)

track <- make_track(u, .x = Xaa, .y = Yaa, .t = datetime, id = id, crs = 3338)
tr <- track %>% nest(data = c(-"id")) # create individual dataframes

tr2 <- tr %>% # downsample to 2-hr fix rate
  mutate(steps = map(data, function(x)
    x %>% track_resample(rate = hours(2), tolerance = minutes(20)))) %>% 
      steps_by_burst()))


track <- make_track(u, .x = Xaa, .y = Yaa, .t = datetime, id = id, crs = 3338)
tr <- track %>% nest(data = c(-"id")) # create individual dataframes

tr2 <- tr %>% # downsample to 2-hr fix rate
  mutate(steps = map(data, function(x)
    x %>% track_resample(rate = hours(2), tolerance = minutes(20)))) %>% 
      steps_by_burst()

# Histogram showing step length

df <- tr2 %>% dplyr::select(id, steps) %>% unnest(cols = steps) 

slHist <- ggplot(data = df, aes(sl_, fill =factor(id))) + 
  geom_histogram(alpha = 0.5) + 
  xlab("step length (m)") + 
  ylab("Number of steps") + 
  theme_classic() +
  theme(legend.position = "bottom") 

ggsave(slHist, filename = "Step Length Histogram for Corr Bears.pdf", 
       path = here("Plots", "OG"),
       dpi = 300,
       width = 7,
       height = 5,
       units = "in")

```

```{r Turning-angle-distribution}

# Density distribution showing turning angle

taDensity <- ggplot(data = steps, aes(ta_, fill = factor(id))) + # check dataframe
  geom_density(alpha = 0.2) + 
  xlab("Turning Angle") + 
  ylab("Density") + 
  theme_classic() +
  theme(legend.position = "bottom") 

ggsave(taDensity, filename = "Turning Angle Density plot for Corr Bears.pdf", 
       path = here("Plots", "OG"),
       dpi = 300,
       width = 7,
       height = 5, 
       units = "in")

```

## Bonepile vs Corridor Comparison

```{r corridor}

# Movement rates for corridor bears

burst1 <- map_df(stepsBurst1, ~as.data.frame(.x), .id = "id") # burst from corridor_used_avail (stepsBurst converted to dataframe)

burst2 <- map_df(stepsBurst2, ~as.data.frame(.x), .id = "id")

burst1a <- na.omit(burst1)
burst2a <- na.omit(burst2)

corr <- bind_rows(burst1a, burst2a)
corr$rate <- corr$sl_ / as.numeric(corr$dt_)


burst1a$Rate <- 

hourly2 <- burst1a %>% mutate(hourly_sl = sl_/2)
hourly4 <- burst2a %>% mutate(hourly_sl = sl_/4)

hourly <- hourly2 %>% bind_rows(hourly4)

mean(hourly$hourly_sl)

hourly$hr

```
```{r movement-rates-at-bonepile}
ltraj <- as.ltraj(xy=u[,c("Xaa","Yaa")], date=u$datetime, id=as.character(u$id))

trajdf <- ld(ltraj)
trajdf$dt <- trajdf$dt/3600 # convert dt to hours

trajdf$Rate <- (trajdf$dist)/(trajdf$dt)

```

```{r paired-t-test}

bpIDs <- unique(trajdf$id)
corrIDs <- unique(corr$id)

corr <- corr %>% filter(id %in% bpIDs)

setdiff(bpIDs, corrIDs)

trajdf <- trajdf %>% filter(!id == "pb_32608.2008")

corrMean <- corr %>%
  group_by(id) %>%
  summarise(meanRate = mean(rate)) %>%
  arrange(id)

bpMean <- trajdf %>%
  group_by(id) %>%
  summarise(meanRate = mean(Rate, na.rm = TRUE)) %>%
  arrange(id)

t.test(corrMean$meanRate, bpMean$meanRate, paired = TRUE)
```





