---
title: "Space Use Summaries"
output:
  html_document:
    df_print: paged
---

```{r echo=FALSE, message=FALSE}
library(ggplot2)
library(adehabitatHR)
library(adehabitatLT)
library(tmap)
library(sf)
library(dplyr)
library(sp)
library(lubridate)
library(tidyr)
library(broom)
```

```{r eval=FALSE}

rm(list = ls())
```



## Map for context. The shapefile is the cropped northern coast of AK; black points are GPS locations. 

```{r}

# Bears

pb <- readRDS('./Data/bears_072321.Rds')

#projection <- "+proj=aea +lat_1=55 +lat_2=65 +lat_0=50 +lon_0=-154 +x_0=0 +y_0=0 +ellps=GRS80 +datum=NAD83 +units=m +no_defs"

pb <- st_as_sf(pb, coords = c('X','Y'), crs = 3338)

# Alaska

us <- st_read('./Data/Spatial/State_Shapefile/States_NAD83_Albers.shp') # From NPS state shapefile

bb <- st_read('C:/Users/akell/OneDrive - Colostate/PhD/Polar_Bears_GIS/Rectangle/Rectangle.shp')
bb <- st_transform(bb, 3338)

ak <- us %>%
  filter(STATE_ABBR == "AK") %>%
  st_transform(3338) 

ak <- st_crop(ak, bb)

plot(st_geometry(ak))
plot(st_geometry(pb), add = TRUE)

```

## Traj summary

```{r}

pb <- cbind(pb, st_coordinates(pb)) # separate coords from geometry columns into X and Y columns

pbdf <- as.data.frame(pb)

traj.pb<-as.ltraj(xy=pbdf[,c("X","Y")], date=pbdf$datetime, id=as.character(pbdf$id))
Summary.traj.pb <- summary(traj.pb)

Summary.traj.pb$DaysTrack <-round(difftime(Summary.traj.pb$date.end,Summary.traj.pb$date.begin, units="days"),digits=1)
Summary.traj.pb$Records <- Summary.traj.pb$nb.reloc-Summary.traj.pb$NAs
Summary.traj.pb$PctComplete <- round((Summary.traj.pb$nb.reloc-Summary.traj.pb$NAs)/Summary.traj.pb$nb.reloc*100,digits=1)

Summary.traj.pb %>%
  dplyr::select(id, date.begin, date.end, DaysTrack) -> akde_tib

```

Mean: `mean(days$days)` 
SD: `sd(days$days)`
Range: `min(days$days)` to `max(days$days)`

## Fixes

```{r eval=TRUE}

traj2 <- ld(traj.pb)

traj2 <- traj2 %>%
  mutate(fix_rate=dt/3600)

fixes <- traj2 %>% 
  group_by(id) %>%
  summarise(n.fixes = n(),
            missing_fixes = sum(is.na(date)),
            fix.pct = n.fixes/missing_fixes)
fixes


```

```{r eval=TRUE}

avgs <- traj2 %>%
  group_by(id) %>%
  na.omit() %>%
  summarise(mean = mean(fix_rate), median = median(fix_rate)) 

avgs

traj2 <- left_join(traj2, avgs)
traj2$median <- round(traj2$median)

table(traj2$id, traj2$median)

# add to df

traj2 %>%
  group_by(id) %>%
  slice_head() %>%
  dplyr::select(mean, median) %>%
  rename(mean_fix = mean) %>%
  rename(median_fix = median) %>%
  left_join(akde_tib) -> akde_tib2


```

## Missing fixes

```{r Missing fixes}

# Divide into groups

one <- filter(traj2, median == 1)
two <- filter(traj2, median > 1 & median < 4)
four <- filter(traj2, median == 4)
eight <- filter(traj2, median == 8)

traj.one <- as.ltraj(xy = one[,c('x','y')], date = one$date, id = one$id)
traj.two <- as.ltraj(xy = two[,c('x','y')], date = two$date, id = two$id)
traj.four <- as.ltraj(xy = four[,c('x','y')], date = four$date, id = four$id)
traj.eight <- as.ltraj(xy = eight[,c('x','y')], date = eight$date, id = eight$id)

# SetNAs

refda <- parse_date_time(paste(min(pb$datetime)), orders = 'ymd HMS', tz = 'US/Alaska') #set reference date 

# Nearly regular (times may still vary slightly)

NA1 <- setNA(traj.one, refda, 1, units = "hour")
NA2 <- setNA(traj.two, refda, 2, units = "hour")
NA4 <- setNA(traj.four, refda, 4, units = "hour")
NA8 <- setNA(traj.eight, refda, 8, units = "hour")

# Regular: accounting for small GPS inconsistencies

na1 <- sett0(NA1, refda, 1, units = "hour")
na2 <- sett0(NA2, refda, 2, units = "hour")
na4 <- sett0(NA4, refda, 4, units = "hour")
na8 <- sett0(NA8, refda, 8, units = "hour")

hrs <- "dt/3600" # so don't have to keep typing this out

# Convert to summary df so can manipulate data (cannot manipulate data when it's an ltraj object)

sum1 <- summary(na1)
sum2 <- summary(na2)
sum4 <- summary(na4)
sum8 <- summary(na8)

sum1 <- sum1 %>%
  mutate(fix_rate = "1 hour")

sum2 <- sum2 %>%
  mutate(fix_rate = "2 hours")

sum4 <- sum4 %>%
  mutate(fix_rate = "4 hours")

sum8 <- sum8 %>%
  mutate(fix_rate = "8 hours")

all_sums <- rbind(sum1, sum2, sum4, sum8)

all_sums <- all_sums %>%
  mutate(missed_fixes_pct = (NAs/(nb.reloc + NAs)*100)) %>%
  dplyr::select(id, missed_fixes_pct)

akde_tib3 <- right_join(all_sums, akde_tib2)

saveRDS(akde_tib3, file = './Data/akde_df.Rds')
```

```{r}

# Extract estimates from akde object

CI_list <- list()

for(i in 1:length(akde)){
  CI_list[[i]] <- akde[[i]]$CI
}

CI_df <- data.frame(matrix(unlist(CI_list), nrow = length(CI_list), byrow = TRUE))
colnames(CI_df) <- c("low", "est", "high")

# Add ID to column

for(i in 1:nrow(CI_df)){
  CI_df$id[i] <- akde_tib$id[i] 
}

final <- akde_tib3 %>%
  left_join(CI_df)

saveRDS(final, file = './Data/Derived-data/akde_list.Rds')

```


## Trajectory analysis - adehabitatLT

```{r Cut-trajs}
# Define function that returns TRUE when time lag between successive relocations is > 24 hours

cut_24hrs <- function(dt) {
return(dt> (24*3600))
}

# Use cutltraj to cut any burst relocations when fix is not taken for > 24 hrs

traj.one.cut <- cutltraj(traj.one, 'cut_24hrs(dt)', nextr = TRUE)
traj.two.cut <- cutltraj(traj.two, 'cut_24hrs(dt)', nextr = TRUE)
traj.four.cut <- cutltraj(traj.four, 'cut_24hrs(dt)', nextr = TRUE)
traj.eight.cut <- cutltraj(traj.eight, 'cut_24hrs(dt)', nextr = TRUE)

plotltr(traj.one[1], "dt/3600") 
```

```{r Make-regular-trajs}

t1reg <- setNA(traj.one.cut, refda, 1, units = "hour")
t2reg <- setNA(traj.two.cut, refda, 1, units = "hour")
t4reg <- setNA(traj.four.cut, refda, 1, units = "hour")
t8reg <- setNA(traj.eight.cut, refda, 1, units = "hour")

t1reg <- sett0(t1reg, refda, 1, units = "hour")
t2reg <- sett0(t2reg, refda, 1, units = "hour")
t4reg <- sett0(t4reg, refda, 1, units = "hour")
t8reg <- sett0(t8reg, refda, 1, units = "hour")
```


```{r}
# Divide trajectories into segments characterized by behavior and then summarize
# Do Poisson??

t1reg.df <- ld(t1reg) # turn into dataframe so can calculate sd of dist
sd(t1reg.df$dist, na.rm = TRUE) # 835 m
mean(t1reg.df$dist, na.rm = TRUE)

tested.means <- round(seq(1, 5000, length =10), 0)

limod <- as.list(paste("dpois(dist=",tested.means,")"))




mod <- modpartltraj(t1reg[3], limod)

mod
bestpartmod(mod)
```







